{{- if .Values.monitoring.enabled -}}
{{- $fullName := include "springboot-helm-chart.fullname" . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "springboot-helm-chart.labels" . | nindent 4 }}
  {{- with .Values.monitoring.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec: 
  endpoints:
    - interval: 15s
      port: http
      scrapeTimeout: 15s
      path: {{ .Values.monitoring.path }}
  selector:
    matchLabels:
      {{- include "springboot-helm-chart.selectorLabels" . | nindent 6 }}
{{- end }}
