apiVersion: v1
kind: Service
metadata:
  name: basic-service
  labels:
    app.kubernetes.io/name: basic-app
spec:
  selector:
    app.kubernetes.io/name: basic-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-port
