apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    route.openshift.io/termination: "edge"
spec:
  ingressClassName: openshift-default
  rules:
    - host: api-demo-service.apps.kdes.upv.es
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: basic-service
              port:
                number: 80
  tls:
    - {}
